### ISSUE TITLE
3CB Loadouts taking priority over fn_ai_init

### ISSUE THREAD

**Issue by bsoWalker** [Beowulf-Arms/BeowulfArms-MissionFramework#8]
Some kind of wait or stop 3CB loadouts from applying when using a Beowulf Loadout

**Comment by Keithenneu** [comment]
3cb is a mess, no easy way of scripting around it.

Easy solution is to put down the 3cb faction module and disable randomisation and loadout application.

**Comment by Keithenneu** [comment]
Function that is responsible for it all is `UK3CB_Factions_Common_fnc_init_EH`
